### PR TITLE
Finder Answer Box A/B Test

### PR DESCRIPTION
**Pull request by DilwoarH**
Test name/reference | Finder answer boxes
-- | --
Problem: Evidence and insight | Our user research has shown that users find long lists of finder results overwhelming.
Solution hypothesis | By highlighting with a box when the top search result is much more relevant than other results, we will make it clear to user where to find the content to meet their need.
URL being tested | https://www.gov.uk/find-eu-exit-guidance-business?keywords=
Metrics we will be measuring | % users clicking the top search result, Time on search results page
How will we know our hypothesis has been validated?/ what does success look like? | If we see a significant increase in user clicking the top result when it is in an answer box, we would also hope to see a reduction of the time before a result was clicked on
Detailed description of hypothesis and measurement | https://docs.google.com/document/d/16LzL-D-v-5E4etLgfUMnbe6okscxcgJsrm0wN7I1EXo
When will the test run? | 28/03/2019
Cookie name | ABTest-FinderAnswerABTest
Weighting split | 50% No answer box
  | 50% Answer box with explainer text
Cookie expiry | 6 weeks
GA Custom Dimension Index | 69
GA Custom Dimension Name | A/B Brexit finder (69)
Custom Dimension Values | A
  | B

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Should we be committing changes to `spec/test-outputs/*`?

**Comment by DilwoarH** [comment]
@vanitabarrett - this is what I used as a reference: https://github.com/alphagov/govuk-cdn-config/pull/133/files

**Comment by leenagupte** [comment]
It looks fine to me. I'm not sure why the tests are failing though,

**Comment by DilwoarH** [comment]
> Seems fine! Don't forget the cookies page (if that's relevant any more)

@sihugh  - I don' think it's relevant anymore - we have this: https://www.gov.uk/help/cookies#multivariate-testing

**Pull request merged**
